
YAML
name: Flutter CI/CD

# متى يعمل هذا الروبوت؟ عند كل عملية رفع (Push) على فرع main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # الخادم الذي سيعمل عليه الكود

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code (فحص الأخطاء)
      run: flutter analyze

    - name: Build APK (بناء التطبيق)
      run: flutter build apk --release

    - name: Upload APK Artifact (رفع التطبيق الجاهز)
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk