# نستخدم سيرفر ويب خفيف جداً لتقديم ملفات التطبيق
FROM nginx:alpine

# ننسخ ملفات نسخة الويب من فلاتر إلى داخل السيرفر
COPY build/web /usr/share/nginx/html

# نفتح البورت رقم 80 ليعمل التطبيق عليه
EXPOSE 80

# تشغيل السيرفر
CMD ["nginx", "-g", "daemon off;"]