name: just_bus_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3  # مكتبة الخرائط الرسمية
  geolocator: ^10.1.0          # لجلب إحداثيات الموقع (GPS)
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^6.0.1        # Kept the newer version and removed the duplicate from above
  audioplayers: ^6.6.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alert.mp3
    - assets/icons/bus_icon.png
    - .env
    